# Generated by Django 5.1.7 on 2025-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
